language: perl
perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
 - "5.18"
before_script:
 - "git config --global user.email 'you@example.com'"
 - "git config --global user.name 'Your Name'"
script: "prove -lr t/"
